# 과제 목표

파이썬 numpy 패키지를 이용해 행렬과 벡터를 정의하고, 이들에 대한 연산을 수행하는 코드를 작성합니다. 

참고자료: [링크](https://numpy.org/doc/stable/user/quickstart.html)

## 행렬 정의

다음의 3x3 행렬 $A$를 정의하는 numpy 코드를 작성하시오.

$$ A = 
\left[
\begin{array}{rrr}
 1 &  2 &  1 \\
 1 &  2 &  3 \\
 2 &  3 & -1
\end{array}
\right]
$$

In [ ]:
import numpy as np
import numpy.linalg

In [ ]:
# 행렬 코딩

## TODO
A = np.array([[1, 2, 1], [1, 2, 3], [2, 3, -1]])

print(A)
print(np.shape(A))

[[ 1  2  1]
 [ 1  2  3]
 [ 2  3 -1]]
(3, 3)


## 벡터 정의
다음의 3-벡터 $\mathbf{b}$를 정의하는 numpy 코드를 작성하시오.
$$ \mathbf{b} = 
\left[
\begin{array}{rrr}
 1 \\
 3 \\
-3
\end{array}
\right]
$$

In [ ]:
# 벡터 코딩

## TODO
b = np.array([1, 3, -3])

print(b)
print(np.shape(b))

[ 1  3 -3]
(3,)


## 역행렬 구하기

3x3 행렬 $A$의 역행렬을 구하는 코드를 numpy의 linalg 서브모듈의 inv() 함수를 이용해 작성하시오.

$$ A^{-1} = 
\left[
\begin{array}{rrr}
 1 &  2 &  1 \\
 1 &  2 &  3 \\
 2 &  3 & -1
\end{array}
\right]^{-1}
$$

참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)

In [ ]:
# 역행렬 구하기

## TODO
A_inv = numpy.linalg.inv(A)

print(A_inv)
print(np.shape(A_inv))

[[-5.5  2.5  2. ]
 [ 3.5 -1.5 -1. ]
 [-0.5  0.5 -0. ]]
(3, 3)


## 역행렬을 이용해 선형시스템 풀기

역행렬을 이용해, 다음의 선형시스템 $A\mathbf{x} = \mathbf{b}$의 해를 구하는 구하는 코드를 작성하시오.

$$ 
\left[
\begin{array}{rrr}
 1 &  2 &  1 \\
 1 &  2 &  3 \\
 2 &  3 & -1
\end{array}
\right]
\left[
\begin{array}{rrr}
x_1 \\
x_2 \\
x_3
\end{array}
\right]
=
\left[
\begin{array}{rrr}
 1 \\
 3 \\
-3
\end{array}
\right]
$$

In [ ]:
# 역행렬을 이용한 선형시스템 Ax=b의 해 구하기

# TODO
x = np.dot(A_inv, b)

print(x)
print(np.shape(x))

[-4.  2.  1.]
(3,)


## 선형시스템의 해 확인

앞서 구한 $\mathbf{x}$가 선형시스템 $A\mathbf{x} = \mathbf{b}$의 해(solution)로서 알맞게 구한 것인지 검증하는 코드를 작성하시오.

방법: $A\mathbf{x}$의 연산결과가 $\mathbf{b}$와 충분히 가까운지를 검증한다. [참고자료: [링크](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)]

In [ ]:
## 결과 검증

# TODO
bb = np.dot(A, x)

if np.allclose(b, bb):
  print("Ok")
else:
  print("something wrong")

Ok
